apiVersion: v1
kind: Secret
metadata:
  name: {{ include "colaig.fullname" . }}
  labels:
    {{- include "colaig.labels" . | nindent 4 }}
type: Opaque
stringData:
  LLM_API_KEY: {{ .Values.llm.apiKey | quote }}
  ALBERT_API_KEY: {{ .Values.llm.apiKey | quote }}
  S3_SECRET_KEY: {{ .Values.storage.s3.secretKey | quote }}
  S3_SESSION_TOKEN: {{ .Values.storage.s3.sessionToken | quote }}
  COLAIG_PLATFORM_API_KEY: {{ .Values.platformApiKey | quote }}
